-- Agregar timestamps a agendas_medicas
ALTER TABLE agendas_medicas ADD COLUMN fecha_creacion TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE agendas_medicas ADD COLUMN fecha_actualizacion TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP;

-- Agregar timestamps a turnos
ALTER TABLE turnos ADD COLUMN fecha_creacion TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE turnos ADD COLUMN fecha_actualizacion TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP;
